package cl.models.pojos;
// Generated 10-08-2017 12:01:10 AM by Hibernate Tools 4.3.1



/**
 * Doctores generated by hbm2java
 */
public class Doctores  implements java.io.Serializable {


     private int id;
     private String nombre;
     private String apellido;
     private int telefono;

    public Doctores() {
    }

    public Doctores(int id, String nombre, String apellido, int telefono) {
       this.id = id;
       this.nombre = nombre;
       this.apellido = apellido;
       this.telefono = telefono;
    }
   
    public int getId() {
        return this.id;
    }
    
    public void setId(int id) {
        this.id = id;
    }
    public String getNombre() {
        return this.nombre;
    }
    
    public void setNombre(String nombre) {
        this.nombre = nombre;
    }
    public String getApellido() {
        return this.apellido;
    }
    
    public void setApellido(String apellido) {
        this.apellido = apellido;
    }
    public int getTelefono() {
        return this.telefono;
    }
    
    public void setTelefono(int telefono) {
        this.telefono = telefono;
    }




}


